Fix -Wall compiler warnings (unused variables etc)
Fix compiler warnings after compiling the project with key warning flags (-Wall
-Wno-unused-function).

These warnings are mostly related to -Wunused-variable and
-Wmaybe-uninitialized. Eg:

 changefile.c:26:19: error: unused variable 'cf_name_append' [-Werror,-Wunused-const-variable]
 static const char cf_name_append[] = ".cf";

 libntfsclone.c: In function 'v10_init':
 libntfsclone.c:171:10: error: unused variable 'i' [-Werror=unused-variable]
       int i;
           ^
 cfchanges.c:152:9: warning: variable 'error' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
     if (argc > 2) {
         ^~~~~~~~

Fixing such compiler warnings will make it easier to identify and resolve more
serious warnings.